{{- include "sch.config.init" (list . "ibm-seas.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
  annotations:
        # This is what defines this resource as a hook. Without this line, the
        # job is considered part of the release.
        "helm.sh/hook": "pre-install, pre-upgrade, pre-rollback"
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "ibm-seas.chart" . }}
    release: {{ .Release.Name }}
data:
  # Configuration values can be set as key-value properties
  seas_config_file: |
    port={{ .Values.service.secure.containerPort }}
    jettyPort={{ .Values.service.jetty.containerPort }} 
    maxHeapSize={{  .Values.seasArgs.maxHeapSize  }}
    {{- if .Values.customFiles }}
    {{- range .Values.customFiles }}
    customFiles={{ . }}
    {{- end }}
    {{- end }}    
  {{- if .Values.customProperties }}
  seas_custom_config_file: | 
    {{- range .Values.customProperties }}
    {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.vmArguments }}
  seas_vm_config_file: | 
    {{- range .Values.vmArguments }}
    {{ . }}
    {{- end }}
  {{- end }}
