{{- include "sch.config.init" (list . "ibm-seas.sch.chart.config.values") }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $appName := include "sch.names.appName" (list .) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{  $fullName  }}
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-seas.chart" .  }}
    release: {{  .Release.Name  }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{  $appName  }}
      app.kubernetes.io/instance: {{  .Release.Name  }}
{{ toYaml .Values.networkPolicy | indent 2 }}

