{{- include "sch.config.init" (list . "ibm-seas.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{  $fullName  }}-preupgrade
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-seas.chart" .  }}
    release: {{  .Release.Name  }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/name: {{  $appName  }}-preupgrade
        app.kubernetes.io/instance: {{  .Release.Name  }}-preupgrade
        app.kubernetes.io/managed-by: {{  .Release.Service  }}-preupgrade
        helm.sh/chart: {{  include "ibm-seas.chart" .  }}-preupgrade
        release: {{  .Release.Name  }}-preupgrade
      annotations:
{{- include "sch.metadata.annotations.metering" (list . .sch.chart.metering "" "" nil) | indent 8 }}

    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ $saName }}
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      {{- end }}
      restartPolicy: Never
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
{{ include "sch.security.securityContext" (list . .sch.chart.podSecurityContext) | indent 8 }}
      affinity:
{{- include "ibm-seas.nodeAffinity" (list . .Values.affinity.nodeAffinity) | indent 8 }}
{{- include "ibm-seas.podAffinity" (list . .Values.affinity.podAffinity) | indent 8 }}
{{- include "ibm-seas.podAntiAffinity" (list . .Values.affinity.podAntiAffinity) | indent 8 }}
      containers:
        - name: pre-upgrade-job
          {{- if .Values.image.digest.enabled }}
          image: "{{  .Values.image.repository  }}@{{ .Values.image.digest.value }}"
          {{- else }}
          image: "{{  .Values.image.repository  }}:{{ .Values.image.tag  }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/seasinstall/maintenance.sh", "upgrade"]
          volumeMounts:
            - mountPath: /seasinstall/IBM/SEAS
              name: seas-pvc
              subPath: SEAS
            - mountPath: /seasinstall/backup
              name: seas-pvc
              subPath: SEAS_BACKUP
          resources:
            limits:
{{ toYaml .Values.resources.limits | indent 14 }}
            requests:
{{ toYaml .Values.resources.requests | indent 14 }}
          securityContext:
{{ include "sch.security.securityContext" (list . .sch.chart.initContainerSecurityContext) | indent 12 }}
      volumes:
      - name: seas-pvc
        persistentVolumeClaim:
          {{- if .Values.persistentVolume.existingClaimName }}
          claimName: {{ .Values.persistentVolume.existingClaimName }}
          {{- else }}
          claimName: {{  $fullName  }}-pvc
          {{- end }}
