{{- include "sch.config.init" (list . "ibm-seas.sch.chart.config.values") }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $saName := include "sch.names.fullCompName" (list . "serviceaccount") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "ibm-seas.chart" . }}
    release: {{ .Release.Name }}
    author: IBM
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    release: {{ .Release.Name }}
    author: IBM
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: non-secure-port
      port: {{ .Values.service.nonSecure.servicePort }}
      targetPort: {{ .Values.service.nonSecure.containerPort }}
      protocol: TCP
    - name: secure-port
      port: {{ .Values.service.secure.servicePort }}
      targetPort: {{ .Values.service.secure.containerPort }}
      protocol: TCP
    - name: jetty-port
      port: {{ .Values.service.jetty.servicePort }}
      targetPort: {{ .Values.service.jetty.containerPort }}
      protocol: TCP
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP }}
  {{- end }}
