qualification:
  levelName: "certified-ibm-cloud-pak"
  levelDescription: "IBM certified container"
  issueDate: "05/2022"
  duration: "12M"
  terms: "Valid from date of issue. Security vulnerability management and enhancements are delivered on the latest version of the chart and images."
prereqs:
  security:
    kubernetes: 
      podSecurityPolicy: 
        name: "ibm-privileged-psp"
    openshift:
      securityContextConstraints:
        name: "ibm-privileged-scc"
    ibmCloudPrivate:
      installerRole:
        name: "Administrator"
  k8sDistros:
    kubernetes:
      semver: ">=1.19.0"
