apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ibm-seas-scc"
  labels:
    app.kubernetes.io/name: ibm-seas-scc
    app.kubernetes.io/instance: ibm-seas-scc
    app.kubernetes.io/managed-by: IBM
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-seas-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
